### PR TITLE
Docker workaround

### PR DESCRIPTION
**Pull request by peresmishnyk**

### CODE REVIEW

**Comment by peresmishnyk** [comment]
Docker workaround, see GitHub issue https://github.com/Roboroads/laravel-tinker/issues/46
Sorry, I am not so familiar with Java and Kotlin but has strong PHP background :)
Tnx for a nice plugin, it is very handy and helpful!

**Comment by Roboroads** [comment]
Interesting! I kind of want to try and see if I can implement this in Kotlin

**Comment by Roboroads** [comment]
I don't want to resort to evalling - so I finally caved and asked Intellij for help on this matter.

**Comment by Roboroads** [comment]
Since I have finally found [a way to make it work](https://github.com/Roboroads/laravel-tinker/commit/9ed1c02030d3b01eab06fba3bb939bcfe3fa16e2) this is not needed anymore. Still thanks for your idea!

**Pull request closed without merging**
